### ISSUE TITLE
chmod error

### ISSUE THREAD

**Issue by ShammanIT** [xvrfr/homeassistant#1]
chmod: невозможно получить доступ к '/usr/sbin/hassio-supervisor': Нет такого файла или каталога

Все по инструкции сделал. Что не так?

**Comment by xvrfr** [comment]
Закомментировал chmod. Пробуй, отпишись, пожалуйста, заработало ли

**Comment by ShammanIT** [comment]
Уже поднял этим скриптом:
curl -sL "https://raw.githubusercontent.com/ntguest/32bit-home-assistant-supervised-installer/master/files/installer-ru.sh" | bash -s -- -m qemux86
Вот отсюда: https://github.com/ntguest/32bit-home-assistant-supervised-installer/blob/main/README-RUSSIAN.md

**Comment by ShammanIT** [comment]
Спасибо, за работу.

**Comment by xvrfr** [comment]
1. Жаль, что я не нашёл труд ntguest, когда мучился  сам :)
2. Изначально я вносил изменения так, чтобы всё было в одном скрипте, не собирался выкладывать. По сути у ntguest более правильный подход к сохранению оригинальности установщика.
